name: Nightly Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  upload-assets:
    strategy:
      matrix:
        info:
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
    runs-on: ${{ matrix.info.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Run build.sh
        run: sh build.sh

      - uses: softprops/action-gh-release@v1
        with:
          files: scripts.zip
          tag_name: nightly
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
